### ISSUE TITLE
ignore phone links

### ISSUE THREAD

**Issue by robfentress** [tjscollins/axe-crawler#3]
Phone links--anchor tags whose `href` attribute begins with `tel:`--should not be scanned.

For example, the following code results in a scan of the URL http://my.domain.com/tel:+11231231234, when it shouldn't:

```html
<p>Phone: <a href="tel:+11231231234">1-123-123-1234</a></p>
```

**Comment by tjscollins** [comment]
Thanks. Fixed in 0.5.5 77e5d5ce03e7d0cb52b165d2ec7fa4d1e42e3636
